export FZF_DEFAULT_COMMAND='rg --files'
export PATH=/usr/local/opt/ruby/bin:$PATH

# This prevents loading by `/bin/sh`, which is not always the same as `/bin/bash`.
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
    source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh
    source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
fi
