#source ~/dotfiles/git/git-completion.bash
#
## Add git completion to aliases
#__git_complete g __git_main
#__git_complete gbD _git_branch
#__git_complete gbd _git_branch
#__git_complete gc _git_commit
#__git_complete gcob _git_checkout
#__git_complete gco _git_checkout
#__git_complete gl _git_log
