filetype plugin indent on
inoremap jk <Esc>

set backspace=indent,eol,start
set clipboard=unnamed " copy to system clipboard
set hidden
set ignorecase
set nocompatible
set number
set ruler

" Softtabs with 4 spaces
set expandtab
set shiftwidth=4
set shiftround
set tabstop=4

syntax on
" color dracula " Dracula isn't installed on this computer

" Italics
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

" Make `gf` create new file if it doesn't exist
nnoremap gf :e <cfile><cr>

" FZF integration
set rtp+=/usr/local/opt/fzf
nnoremap <leader>t :FZF<cr>
