filetype plugin indent on
inoremap jk <Esc>

set backspace=indent,eol,start
set clipboard=unnamed " copy to system clipboard
set hidden
set ignorecase
set nocompatible
set number
set ruler

" Softtabs with 4 spaces
set expandtab
set shiftwidth=4
set shiftround
set tabstop=4

syntax on
color dracula

" Italics
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
