touch ~/.hushlogin
#export PS1='\W $ '
#export PS1='\W λ '
#export PS1='\W ℂ '
#export PS1='\W ∀x ∈ ℂ: '
#export PS1='\W ℍ '
#export PS1='\W ℕ '
#export PS1='\W ℙ '
export PS1='\W n ∈ ℙ: '
#export PS1='\W ℚ '
#export PS1='\W ℝ '
#export PS1='\W ℤ '
#export PS1='\W χ '
#export PS1='\W σ(n) '
#export PS1='\W ∀ '

source ~/.bash_profile.work
source ~/bin/bash_profile.bin
source ~/dotfiles/bash_profile.dotfiles
